<?php
    require_once('smarty/Smarty.class.php');
    require_once('include/request.inc.php');
    require_once('include/textstrength.inc.php');
    require_once('include/checkparams.inc.php');
    require_once('include/user.inc.php');
    require_once('include/userinfoselect.inc.php');
    require_once('include/config.inc.php');
    require_once('include/database.inc.php');
    require_once('include/save_survey.inc.php');
    require_once('include/survey.inc.php');
    require_once('include/template.inc.php'); 
    require_once('include/layout.inc.php'); 
    require_once('include/convert.inc.php');  
    require_once('include/files.inc.php'); 
    require_once('include/rate.inc.php'); 
    require_once('include/htmllists.inc.php');    
    
    session_start();
    dbInitialConnect();